# Generated by Django 4.2.7 on 2023-11-18 01:26

from django.db import migrations, models

# makemigrationsをした際の履歴が残る
class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField()),
                ("intro", models.TextField()),
                ("body", models.TextField()),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
